import { requireAdmin } from '@/lib/auth/akses';
import { promoAdmin } from '@/lib/data/admin';
import { hapusPromoAdmin } from '@/actions/admin';
import { formatRupiah, formatTanggalSingkat } from '@/lib/format';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { AdminHeading, AdminEmpty, AksiIkon, safeQuery } from '@/components/admin/presentation';
import { PromoAdminForm, AdminMutationButton } from '@/components/admin/forms';
const datetimeWIB = (date: Date) => new Date(date.getTime() + 7 * 3_600_000).toISOString().slice(0, 16);
export default async function HalamanPromoAdmin({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin('/admin/promo');
  const promos = await promoAdmin(); const edit = safeQuery((await searchParams).edit); const selected = promos.find((p) => p.code === edit);
  return <><AdminHeading title="Kode promo" description="Kelola diskon, periode promo, kuota, dan batas pemakaian pelanggan." />{promos.length ? <div className="mb-6 rounded-xl border bg-background"><Table><TableHeader><TableRow><TableHead>Kode promo</TableHead><TableHead>Diskon</TableHead><TableHead>Pemakaian / kuota</TableHead><TableHead>Berakhir</TableHead><TableHead>Status</TableHead><TableHead>Tindakan</TableHead></TableRow></TableHeader><TableBody>{promos.map((p) => <TableRow key={p.code}><TableCell><p className="font-semibold">{p.code}</p><p className="text-xs text-muted-foreground">{p.description}</p></TableCell><TableCell>{p.type === 'PERCENT' ? `${p.value}%` : formatRupiah(p.value)}</TableCell><TableCell>{p.usedCount} / {p.quota ?? 'Tanpa batas'}</TableCell><TableCell>{formatTanggalSingkat(p.expiresAt)}</TableCell><TableCell>{!p.isActive ? 'Nonaktif' : p.expiresAt < new Date() ? 'Kedaluwarsa' : p.startsAt > new Date() ? 'Terjadwal' : 'Aktif'}</TableCell><TableCell><div className="flex flex-wrap gap-2"><AksiIkon href={`/admin/promo?edit=${encodeURIComponent(p.code)}`} label="Edit" jenis="edit" />{p._count.usages === 0 && p.usedCount === 0 && <AdminMutationButton action={hapusPromoAdmin} data={{ code: p.code }} label="Hapus" confirmText={`Hapus kode promo ${p.code}?`} />}</div></TableCell></TableRow>)}</TableBody></Table></div> : <div className="mb-6"><AdminEmpty>Belum ada kode promo. Buat promo pertama untuk pelanggan.</AdminEmpty></div>}<Card><CardHeader><CardTitle>{selected ? `Edit promo ${selected.code}` : 'Tambah kode promo'}</CardTitle>{selected && <AksiIkon href="/admin/promo" label="Tambah promo baru" jenis="tambah" />}</CardHeader><CardContent><PromoAdminForm key={selected?.code ?? 'new'} promo={selected ? { code: selected.code, description: selected.description, type: selected.type, value: selected.value, minSubtotal: selected.minSubtotal, maxDiscount: selected.maxDiscount, quota: selected.quota, perUserLimit: selected.perUserLimit, startsAt: datetimeWIB(selected.startsAt), expiresAt: datetimeWIB(selected.expiresAt), isActive: selected.isActive } : undefined} /></CardContent></Card></>;
}
