import Link from 'next/link';
import { requireAdmin } from '@/lib/auth/akses';
import { daftarPesananAdmin } from '@/lib/data/admin';
import { LABEL_STATUS_PESANAN, LABEL_STATUS_PEMBAYARAN, type OrderStatus } from '@/lib/pesanan/status';
import { formatRupiah, formatTanggalSingkat } from '@/lib/format';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { AdminHeading, AdminEmpty, StatusBadge, PaginationAdmin, safePage, safeQuery } from '@/components/admin/presentation';
export default async function HalamanPesananAdmin({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin('/admin/pesanan');
  const params = await searchParams; const q = safeQuery(params.q); const status = safeQuery(params.status); const page = safePage(params.page);
  const selectedStatus = Object.hasOwn(LABEL_STATUS_PESANAN, status) ? status as OrderStatus : undefined;
  const data = await daftarPesananAdmin(selectedStatus, q, page);
  return <><AdminHeading title="Pesanan" description="Proses pesanan, verifikasi pembayaran, dan pantau pengiriman." /><form className="mb-6 flex flex-col items-end gap-3 sm:flex-row"><div className="w-full flex-1 space-y-1"><Label htmlFor="q">Cari pesanan</Label><Input className="min-h-10" id="q" name="q" defaultValue={q} placeholder="Nomor pesanan atau nama pembeli" /></div><div className="w-full space-y-1 sm:w-52"><Label htmlFor="status">Status pesanan</Label><select className="min-h-10 w-full rounded-lg border bg-background px-3 text-sm" id="status" name="status" defaultValue={selectedStatus ?? ''}><option value="">Semua status</option>{Object.entries(LABEL_STATUS_PESANAN).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><Button className="min-h-10" type="submit">Terapkan</Button></form>{data.items.length ? <div className="rounded-xl border bg-background"><Table><TableHeader><TableRow><TableHead>Pesanan</TableHead><TableHead>Pembeli</TableHead><TableHead>Total</TableHead><TableHead>Pembayaran</TableHead><TableHead>Status</TableHead><TableHead className="text-right"><span className="sr-only">Tindakan</span></TableHead></TableRow></TableHeader><TableBody>{data.items.map((order) => <TableRow key={order.id}><TableCell><Link href={`/admin/pesanan/${order.id}`} className="whitespace-nowrap font-medium text-foreground underline-offset-4 hover:text-primary hover:underline focus-visible:underline">{order.orderNumber}</Link><p className="text-xs text-muted-foreground">{formatTanggalSingkat(order.createdAt)}</p></TableCell><TableCell>{order.user.name}</TableCell><TableCell className="whitespace-nowrap tabular-nums">{formatRupiah(order.grandTotal)}</TableCell><TableCell>{LABEL_STATUS_PEMBAYARAN[order.paymentStatus]}</TableCell><TableCell><StatusBadge status={order.status} /></TableCell><TableCell className="text-right"><Button asChild variant="outline" size="sm" className="min-h-9"><Link href={`/admin/pesanan/${order.id}`} aria-label={`Lihat detail ${order.orderNumber}`}>Detail</Link></Button></TableCell></TableRow>)}</TableBody></Table></div> : <AdminEmpty>Belum ada pesanan yang cocok dengan filter ini.</AdminEmpty>}<PaginationAdmin page={page} count={data.count} pathname="/admin/pesanan" query={{ q, status }} /></>;
}
